### ISSUE TITLE
问题 反馈

### ISSUE THREAD

**Issue by fuqiang03** [kongfl888/luci-app-kcpufreq#1]
![QQ截图20200729203637](https://user-images.githubusercontent.com/26851715/88800875-69207800-d1db-11ea-9bbf-460e57166f25.png)
主库的master 和luci

**Comment by kongfl888** [comment]
首页那里 固件版本 复制下 (openwrt+luci)

**Comment by fuqiang03** [comment]
![QQ截图20200819185737](https://user-images.githubusercontent.com/26851715/90626694-e163e180-e24d-11ea-8fa5-bfcaf118f9cc.png)

**Comment by kongfl888** [comment]
测试下 [V1.2](https://github.com/kongfl888/luci-app-kcpufreq/releases/tag/v1.2-1)

**Comment by kongfl888** [comment]
测试下 [V1.2](https://github.com/kongfl888/luci-app-kcpufreq/releases/tag/v1.2-1)

**Comment by fuqiang03** [comment]
在虚拟机下运行 esxi7.0b Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
运行结果如下:
页面可正常进入
![QQ截图20200819225224](https://user-images.githubusercontent.com/26851715/90651036-2e0be480-e26f-11ea-9b8d-0832838708b3.png)
![QQ截图20200819225416](https://user-images.githubusercontent.com/26851715/90651039-2e0be480-e26f-11ea-8d3f-816d6acbc5bd.png)

**Comment by fuqiang03** [comment]
这些选项我记得在内核配上见过
cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq
提示目录不存在
不知道是否需要其他依赖吗
root@OpenWrt:/# /etc/init.d/kcpufreq start                                                                                                                                              
cat: can't open '/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq': No such file or directory                                                                                      
cat: can't open '/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq': No such file or directory 
![QQ截图20200819231102](https://user-images.githubusercontent.com/26851715/90653051-4f6dd000-e271-11ea-986e-c9b7a80da9f4.png)

**Comment by kongfl888** [comment]
对，内核编译的时候需要配置上
------
CONFIG_CPU_FREQ=y
CONFIG_CPU_FREQ_GOV_xxx 也打y xxx表示你需要编入的调度器（ONDEMAND等）

如果内核没有这些组件，系统安装完后是添加加不了的（没有对应的软件包）

**Comment by kongfl888** [comment]
对，内核编译的时候需要配置上

CONFIG_CPU_FREQ=y
CONFIG_CPU_FREQ_GOV_xxx 也打y xxx表示你需要编入的调度器（ONDEMAND等）

如果内核没有这些组件，系统安装完后是添加不了的（没有对应的软件包）

**Comment by kongfl888** [comment]
ls /sys/devices/system/cpu/cpu0/cpufreq 看看有没有东东

**Comment by kongfl888** [comment]
ls /sys/devices/system/cpu/cpufreq

**Comment by fuqiang03** [comment]
能开的配置都开了 
![QQ截图20200821123121](https://user-images.githubusercontent.com/26851715/90852521-42083100-e3aa-11ea-8d0b-2ba615d3cdb7.png)
![QQ截图20200821123130](https://user-images.githubusercontent.com/26851715/90852523-42a0c780-e3aa-11ea-83cd-8e0ea91a9de8.png)
![QQ截图20200821123316](https://user-images.githubusercontent.com/26851715/90852618-81cf1880-e3aa-11ea-87cc-6497bdd5856e.png)
但是你说的目录下 依然什么也没有
请问的内核 和配置是什么样的
